# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-OpenSSL-RSA-Encryption-Decryption' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift-OpenSSL-RSA-Encryption-Decryption
    pod 'OpenSSL-iOS','~> 1.0.204'
end
