# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SqliteTest' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'SQLite.swift', '~> 0.11.2'
  # Pods for SqliteTest

end
